include:
- project: iiidevops-templates/ci-template
  ref: v2.11.0
  file: ci/template.gitlab-ci.yml
- project: iiidevops-templates/ci-template
  ref: v2.11.0
  file: job/DeployDatabase-MS.gitlab-ci.yml

stages:
- initial
- scan
- build
- deploy
- test
- userjobs

Deploy--Database (MS-SQL):
  variables:
    iiidevops: deploy-db
    CHART_DB_GUI: 'true'
    CHART_DB_PASSWORD: DevOps_123
    CHART_DB_TAG: 2019-CU10-ubuntu-20.04
    CHART_VOLUME_ENABLED: 'false'

Deploy--Wait DB deployment:
  variables:
    iiidevops: deploy-db
    max_wait: 128
